name: release_ghcr

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get tag version
      run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Publish Docker image to GitHub Container Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ github.repository }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tags: "latest,${{ env.TAG_VERSION }}"
